// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package com.golding.tvbcloud;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tvbcloud.CCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求  
     * </pre>
     *
     * <code>int32 commandCode = 1;</code>
     */
    int getCommandCode();

    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string commandParam = 2;</code>
     */
    String getCommandParam();
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string commandParam = 2;</code>
     */
    com.google.protobuf.ByteString
        getCommandParamBytes();
  }
  /**
   * Protobuf type {@code tvbcloud.CCommand}
   */
  public  static final class CCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tvbcloud.CCommand)
      CCommandOrBuilder {
    // Use CCommand.newBuilder() to construct.
    private CCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CCommand() {
      commandCode_ = 0;
      commandParam_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              commandCode_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              commandParam_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Command.internal_static_tvbcloud_CCommand_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Command.internal_static_tvbcloud_CCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CCommand.class, Builder.class);
    }

    public static final int COMMANDCODE_FIELD_NUMBER = 1;
    private int commandCode_;
    /**
     * <pre>
     * 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求  
     * </pre>
     *
     * <code>int32 commandCode = 1;</code>
     */
    public int getCommandCode() {
      return commandCode_;
    }

    public static final int COMMANDPARAM_FIELD_NUMBER = 2;
    private volatile Object commandParam_;
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string commandParam = 2;</code>
     */
    public String getCommandParam() {
      Object ref = commandParam_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        commandParam_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *
     * </pre>
     *
     * <code>string commandParam = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCommandParamBytes() {
      Object ref = commandParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        commandParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandCode_ != 0) {
        output.writeInt32(1, commandCode_);
      }
      if (!getCommandParamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, commandParam_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandCode_);
      }
      if (!getCommandParamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, commandParam_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CCommand)) {
        return super.equals(obj);
      }
      CCommand other = (CCommand) obj;

      boolean result = true;
      result = result && (getCommandCode()
          == other.getCommandCode());
      result = result && getCommandParam()
          .equals(other.getCommandParam());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMANDCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCommandCode();
      hash = (37 * hash) + COMMANDPARAM_FIELD_NUMBER;
      hash = (53 * hash) + getCommandParam().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tvbcloud.CCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tvbcloud.CCommand)
        CCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Command.internal_static_tvbcloud_CCommand_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Command.internal_static_tvbcloud_CCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CCommand.class, Builder.class);
      }

      // Construct using com.golding.tvbcloud.Command.CCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        commandCode_ = 0;

        commandParam_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Command.internal_static_tvbcloud_CCommand_descriptor;
      }

      public CCommand getDefaultInstanceForType() {
        return CCommand.getDefaultInstance();
      }

      public CCommand build() {
        CCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CCommand buildPartial() {
        CCommand result = new CCommand(this);
        result.commandCode_ = commandCode_;
        result.commandParam_ = commandParam_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CCommand) {
          return mergeFrom((CCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CCommand other) {
        if (other == CCommand.getDefaultInstance()) return this;
        if (other.getCommandCode() != 0) {
          setCommandCode(other.getCommandCode());
        }
        if (!other.getCommandParam().isEmpty()) {
          commandParam_ = other.commandParam_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commandCode_ ;
      /**
       * <pre>
       * 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求  
       * </pre>
       *
       * <code>int32 commandCode = 1;</code>
       */
      public int getCommandCode() {
        return commandCode_;
      }
      /**
       * <pre>
       * 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求  
       * </pre>
       *
       * <code>int32 commandCode = 1;</code>
       */
      public Builder setCommandCode(int value) {
        
        commandCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求  
       * </pre>
       *
       * <code>int32 commandCode = 1;</code>
       */
      public Builder clearCommandCode() {
        
        commandCode_ = 0;
        onChanged();
        return this;
      }

      private Object commandParam_ = "";
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string commandParam = 2;</code>
       */
      public String getCommandParam() {
        Object ref = commandParam_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          commandParam_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string commandParam = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCommandParamBytes() {
        Object ref = commandParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          commandParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string commandParam = 2;</code>
       */
      public Builder setCommandParam(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commandParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string commandParam = 2;</code>
       */
      public Builder clearCommandParam() {
        
        commandParam_ = getDefaultInstance().getCommandParam();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *
       * </pre>
       *
       * <code>string commandParam = 2;</code>
       */
      public Builder setCommandParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commandParam_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tvbcloud.CCommand)
    }

    // @@protoc_insertion_point(class_scope:tvbcloud.CCommand)
    private static final CCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CCommand();
    }

    public static CCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CCommand>
        PARSER = new com.google.protobuf.AbstractParser<CCommand>() {
      public CCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CCommand> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CCommand> getParserForType() {
      return PARSER;
    }

    public CCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tvbcloud_CCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tvbcloud_CCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rCommand.proto\022\010tvbcloud\"5\n\010CCommand\022\023\n" +
      "\013commandCode\030\001 \001(\005\022\024\n\014commandParam\030\002 \001(\t" +
      "B>\n\024com.golding.tvbcloudB\007Command\252\002\034com." +
      "golding.tvbcloud.Commandb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tvbcloud_CCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tvbcloud_CCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tvbcloud_CCommand_descriptor,
        new String[] { "CommandCode", "CommandParam", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
