// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Logon.proto

package com.golding.tvbcloud;

public final class Logon {
  private Logon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CLogonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tvbcloud.CLogon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1.Android端   2.pc端
     * </pre>
     *
     * <code>int32 terminal = 1;</code>
     */
    int getTerminal();

    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 2;</code>
     */
    String getDevId();
    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDevIdBytes();

    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 3;</code>
     */
    String getSeatNum();
    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 3;</code>
     */
    com.google.protobuf.ByteString
        getSeatNumBytes();

    /**
     * <pre>
     *安卓客户端ip地址
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    String getIp();
    /**
     * <pre>
     *安卓客户端ip地址
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <pre>
     *安卓客户端版本号
     * </pre>
     *
     * <code>string apkVer = 5;</code>
     */
    String getApkVer();
    /**
     * <pre>
     *安卓客户端版本号
     * </pre>
     *
     * <code>string apkVer = 5;</code>
     */
    com.google.protobuf.ByteString
        getApkVerBytes();

    /**
     * <pre>
     *安卓系统版本号
     * </pre>
     *
     * <code>string sysVer = 6;</code>
     */
    String getSysVer();
    /**
     * <pre>
     *安卓系统版本号
     * </pre>
     *
     * <code>string sysVer = 6;</code>
     */
    com.google.protobuf.ByteString
        getSysVerBytes();
  }
  /**
   * Protobuf type {@code tvbcloud.CLogon}
   */
  public  static final class CLogon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tvbcloud.CLogon)
      CLogonOrBuilder {
    // Use CLogon.newBuilder() to construct.
    private CLogon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CLogon() {
      terminal_ = 0;
      devId_ = "";
      seatNum_ = "";
      ip_ = "";
      apkVer_ = "";
      sysVer_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CLogon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              terminal_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              devId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              seatNum_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              apkVer_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              sysVer_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Logon.internal_static_tvbcloud_CLogon_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Logon.internal_static_tvbcloud_CLogon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CLogon.class, Builder.class);
    }

    public static final int TERMINAL_FIELD_NUMBER = 1;
    private int terminal_;
    /**
     * <pre>
     *1.Android端   2.pc端
     * </pre>
     *
     * <code>int32 terminal = 1;</code>
     */
    public int getTerminal() {
      return terminal_;
    }

    public static final int DEVID_FIELD_NUMBER = 2;
    private volatile Object devId_;
    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 2;</code>
     */
    public String getDevId() {
      Object ref = devId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        devId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDevIdBytes() {
      Object ref = devId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEATNUM_FIELD_NUMBER = 3;
    private volatile Object seatNum_;
    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 3;</code>
     */
    public String getSeatNum() {
      Object ref = seatNum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        seatNum_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSeatNumBytes() {
      Object ref = seatNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        seatNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 4;
    private volatile Object ip_;
    /**
     * <pre>
     *安卓客户端ip地址
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    public String getIp() {
      Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓客户端ip地址
     * </pre>
     *
     * <code>string ip = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APKVER_FIELD_NUMBER = 5;
    private volatile Object apkVer_;
    /**
     * <pre>
     *安卓客户端版本号
     * </pre>
     *
     * <code>string apkVer = 5;</code>
     */
    public String getApkVer() {
      Object ref = apkVer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        apkVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓客户端版本号
     * </pre>
     *
     * <code>string apkVer = 5;</code>
     */
    public com.google.protobuf.ByteString
        getApkVerBytes() {
      Object ref = apkVer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        apkVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSVER_FIELD_NUMBER = 6;
    private volatile Object sysVer_;
    /**
     * <pre>
     *安卓系统版本号
     * </pre>
     *
     * <code>string sysVer = 6;</code>
     */
    public String getSysVer() {
      Object ref = sysVer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sysVer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓系统版本号
     * </pre>
     *
     * <code>string sysVer = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSysVerBytes() {
      Object ref = sysVer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sysVer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (terminal_ != 0) {
        output.writeInt32(1, terminal_);
      }
      if (!getDevIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, devId_);
      }
      if (!getSeatNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, seatNum_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ip_);
      }
      if (!getApkVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, apkVer_);
      }
      if (!getSysVerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sysVer_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (terminal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, terminal_);
      }
      if (!getDevIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, devId_);
      }
      if (!getSeatNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, seatNum_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ip_);
      }
      if (!getApkVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, apkVer_);
      }
      if (!getSysVerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sysVer_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CLogon)) {
        return super.equals(obj);
      }
      CLogon other = (CLogon) obj;

      boolean result = true;
      result = result && (getTerminal()
          == other.getTerminal());
      result = result && getDevId()
          .equals(other.getDevId());
      result = result && getSeatNum()
          .equals(other.getSeatNum());
      result = result && getIp()
          .equals(other.getIp());
      result = result && getApkVer()
          .equals(other.getApkVer());
      result = result && getSysVer()
          .equals(other.getSysVer());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERMINAL_FIELD_NUMBER;
      hash = (53 * hash) + getTerminal();
      hash = (37 * hash) + DEVID_FIELD_NUMBER;
      hash = (53 * hash) + getDevId().hashCode();
      hash = (37 * hash) + SEATNUM_FIELD_NUMBER;
      hash = (53 * hash) + getSeatNum().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + APKVER_FIELD_NUMBER;
      hash = (53 * hash) + getApkVer().hashCode();
      hash = (37 * hash) + SYSVER_FIELD_NUMBER;
      hash = (53 * hash) + getSysVer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CLogon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CLogon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CLogon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CLogon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CLogon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CLogon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CLogon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CLogon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CLogon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CLogon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CLogon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CLogon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CLogon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tvbcloud.CLogon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tvbcloud.CLogon)
        CLogonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Logon.internal_static_tvbcloud_CLogon_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Logon.internal_static_tvbcloud_CLogon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CLogon.class, Builder.class);
      }

      // Construct using com.golding.tvbcloud.Logon.CLogon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        terminal_ = 0;

        devId_ = "";

        seatNum_ = "";

        ip_ = "";

        apkVer_ = "";

        sysVer_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Logon.internal_static_tvbcloud_CLogon_descriptor;
      }

      public CLogon getDefaultInstanceForType() {
        return CLogon.getDefaultInstance();
      }

      public CLogon build() {
        CLogon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CLogon buildPartial() {
        CLogon result = new CLogon(this);
        result.terminal_ = terminal_;
        result.devId_ = devId_;
        result.seatNum_ = seatNum_;
        result.ip_ = ip_;
        result.apkVer_ = apkVer_;
        result.sysVer_ = sysVer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CLogon) {
          return mergeFrom((CLogon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CLogon other) {
        if (other == CLogon.getDefaultInstance()) return this;
        if (other.getTerminal() != 0) {
          setTerminal(other.getTerminal());
        }
        if (!other.getDevId().isEmpty()) {
          devId_ = other.devId_;
          onChanged();
        }
        if (!other.getSeatNum().isEmpty()) {
          seatNum_ = other.seatNum_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getApkVer().isEmpty()) {
          apkVer_ = other.apkVer_;
          onChanged();
        }
        if (!other.getSysVer().isEmpty()) {
          sysVer_ = other.sysVer_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CLogon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CLogon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int terminal_ ;
      /**
       * <pre>
       *1.Android端   2.pc端
       * </pre>
       *
       * <code>int32 terminal = 1;</code>
       */
      public int getTerminal() {
        return terminal_;
      }
      /**
       * <pre>
       *1.Android端   2.pc端
       * </pre>
       *
       * <code>int32 terminal = 1;</code>
       */
      public Builder setTerminal(int value) {
        
        terminal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1.Android端   2.pc端
       * </pre>
       *
       * <code>int32 terminal = 1;</code>
       */
      public Builder clearTerminal() {
        
        terminal_ = 0;
        onChanged();
        return this;
      }

      private Object devId_ = "";
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 2;</code>
       */
      public String getDevId() {
        Object ref = devId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 2;</code>
       */
      public Builder setDevId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 2;</code>
       */
      public Builder clearDevId() {
        
        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 2;</code>
       */
      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devId_ = value;
        onChanged();
        return this;
      }

      private Object seatNum_ = "";
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 3;</code>
       */
      public String getSeatNum() {
        Object ref = seatNum_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          seatNum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSeatNumBytes() {
        Object ref = seatNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          seatNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 3;</code>
       */
      public Builder setSeatNum(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seatNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 3;</code>
       */
      public Builder clearSeatNum() {
        
        seatNum_ = getDefaultInstance().getSeatNum();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 3;</code>
       */
      public Builder setSeatNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seatNum_ = value;
        onChanged();
        return this;
      }

      private Object ip_ = "";
      /**
       * <pre>
       *安卓客户端ip地址
       * </pre>
       *
       * <code>string ip = 4;</code>
       */
      public String getIp() {
        Object ref = ip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端ip地址
       * </pre>
       *
       * <code>string ip = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端ip地址
       * </pre>
       *
       * <code>string ip = 4;</code>
       */
      public Builder setIp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端ip地址
       * </pre>
       *
       * <code>string ip = 4;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端ip地址
       * </pre>
       *
       * <code>string ip = 4;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private Object apkVer_ = "";
      /**
       * <pre>
       *安卓客户端版本号
       * </pre>
       *
       * <code>string apkVer = 5;</code>
       */
      public String getApkVer() {
        Object ref = apkVer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          apkVer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端版本号
       * </pre>
       *
       * <code>string apkVer = 5;</code>
       */
      public com.google.protobuf.ByteString
          getApkVerBytes() {
        Object ref = apkVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          apkVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端版本号
       * </pre>
       *
       * <code>string apkVer = 5;</code>
       */
      public Builder setApkVer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        apkVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端版本号
       * </pre>
       *
       * <code>string apkVer = 5;</code>
       */
      public Builder clearApkVer() {
        
        apkVer_ = getDefaultInstance().getApkVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端版本号
       * </pre>
       *
       * <code>string apkVer = 5;</code>
       */
      public Builder setApkVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        apkVer_ = value;
        onChanged();
        return this;
      }

      private Object sysVer_ = "";
      /**
       * <pre>
       *安卓系统版本号
       * </pre>
       *
       * <code>string sysVer = 6;</code>
       */
      public String getSysVer() {
        Object ref = sysVer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sysVer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓系统版本号
       * </pre>
       *
       * <code>string sysVer = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSysVerBytes() {
        Object ref = sysVer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sysVer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓系统版本号
       * </pre>
       *
       * <code>string sysVer = 6;</code>
       */
      public Builder setSysVer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sysVer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓系统版本号
       * </pre>
       *
       * <code>string sysVer = 6;</code>
       */
      public Builder clearSysVer() {
        
        sysVer_ = getDefaultInstance().getSysVer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓系统版本号
       * </pre>
       *
       * <code>string sysVer = 6;</code>
       */
      public Builder setSysVerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sysVer_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tvbcloud.CLogon)
    }

    // @@protoc_insertion_point(class_scope:tvbcloud.CLogon)
    private static final CLogon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CLogon();
    }

    public static CLogon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CLogon>
        PARSER = new com.google.protobuf.AbstractParser<CLogon>() {
      public CLogon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CLogon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CLogon> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CLogon> getParserForType() {
      return PARSER;
    }

    public CLogon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tvbcloud_CLogon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tvbcloud_CLogon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Logon.proto\022\010tvbcloud\"f\n\006CLogon\022\020\n\010ter" +
      "minal\030\001 \001(\005\022\r\n\005devId\030\002 \001(\t\022\017\n\007seatNum\030\003 " +
      "\001(\t\022\n\n\002ip\030\004 \001(\t\022\016\n\006apkVer\030\005 \001(\t\022\016\n\006sysVe" +
      "r\030\006 \001(\tB:\n\024com.golding.tvbcloudB\005Logon\252\002" +
      "\032com.golding.tvbcloud.Logonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tvbcloud_CLogon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tvbcloud_CLogon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tvbcloud_CLogon_descriptor,
        new String[] { "Terminal", "DevId", "SeatNum", "Ip", "ApkVer", "SysVer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
