// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Respond.proto

package com.golding.tvbcloud;

public final class Respond {
  private Respond() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CRespondOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tvbcloud.CRespond)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 1;</code>
     */
    String getDevId();
    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDevIdBytes();

    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 2;</code>
     */
    String getSeatNum();
    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 2;</code>
     */
    com.google.protobuf.ByteString
        getSeatNumBytes();

    /**
     * <pre>
     *0.接收投票信息 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求 
     * </pre>
     *
     * <code>int32 respondCode = 3;</code>
     */
    int getRespondCode();

    /**
     * <pre>
     *200.成功   其他失败
     * </pre>
     *
     * <code>string respondParam = 4;</code>
     */
    String getRespondParam();
    /**
     * <pre>
     *200.成功   其他失败
     * </pre>
     *
     * <code>string respondParam = 4;</code>
     */
    com.google.protobuf.ByteString
        getRespondParamBytes();
  }
  /**
   * Protobuf type {@code tvbcloud.CRespond}
   */
  public  static final class CRespond extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tvbcloud.CRespond)
      CRespondOrBuilder {
    // Use CRespond.newBuilder() to construct.
    private CRespond(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CRespond() {
      devId_ = "";
      seatNum_ = "";
      respondCode_ = 0;
      respondParam_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CRespond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              devId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              seatNum_ = s;
              break;
            }
            case 24: {

              respondCode_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              respondParam_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Respond.internal_static_tvbcloud_CRespond_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Respond.internal_static_tvbcloud_CRespond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CRespond.class, Builder.class);
    }

    public static final int DEVID_FIELD_NUMBER = 1;
    private volatile Object devId_;
    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 1;</code>
     */
    public String getDevId() {
      Object ref = devId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        devId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓客户端设备id
     * </pre>
     *
     * <code>string devId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDevIdBytes() {
      Object ref = devId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEATNUM_FIELD_NUMBER = 2;
    private volatile Object seatNum_;
    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 2;</code>
     */
    public String getSeatNum() {
      Object ref = seatNum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        seatNum_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安卓客户端座位号
     * </pre>
     *
     * <code>string seatNum = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSeatNumBytes() {
      Object ref = seatNum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        seatNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONDCODE_FIELD_NUMBER = 3;
    private int respondCode_;
    /**
     * <pre>
     *0.接收投票信息 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求 
     * </pre>
     *
     * <code>int32 respondCode = 3;</code>
     */
    public int getRespondCode() {
      return respondCode_;
    }

    public static final int RESPONDPARAM_FIELD_NUMBER = 4;
    private volatile Object respondParam_;
    /**
     * <pre>
     *200.成功   其他失败
     * </pre>
     *
     * <code>string respondParam = 4;</code>
     */
    public String getRespondParam() {
      Object ref = respondParam_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        respondParam_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *200.成功   其他失败
     * </pre>
     *
     * <code>string respondParam = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRespondParamBytes() {
      Object ref = respondParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        respondParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDevIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, devId_);
      }
      if (!getSeatNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, seatNum_);
      }
      if (respondCode_ != 0) {
        output.writeInt32(3, respondCode_);
      }
      if (!getRespondParamBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, respondParam_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDevIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, devId_);
      }
      if (!getSeatNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, seatNum_);
      }
      if (respondCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, respondCode_);
      }
      if (!getRespondParamBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, respondParam_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CRespond)) {
        return super.equals(obj);
      }
      CRespond other = (CRespond) obj;

      boolean result = true;
      result = result && getDevId()
          .equals(other.getDevId());
      result = result && getSeatNum()
          .equals(other.getSeatNum());
      result = result && (getRespondCode()
          == other.getRespondCode());
      result = result && getRespondParam()
          .equals(other.getRespondParam());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVID_FIELD_NUMBER;
      hash = (53 * hash) + getDevId().hashCode();
      hash = (37 * hash) + SEATNUM_FIELD_NUMBER;
      hash = (53 * hash) + getSeatNum().hashCode();
      hash = (37 * hash) + RESPONDCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRespondCode();
      hash = (37 * hash) + RESPONDPARAM_FIELD_NUMBER;
      hash = (53 * hash) + getRespondParam().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CRespond parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CRespond parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CRespond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CRespond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CRespond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CRespond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CRespond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CRespond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CRespond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CRespond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CRespond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CRespond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CRespond prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tvbcloud.CRespond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tvbcloud.CRespond)
        CRespondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Respond.internal_static_tvbcloud_CRespond_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Respond.internal_static_tvbcloud_CRespond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CRespond.class, Builder.class);
      }

      // Construct using com.golding.tvbcloud.Respond.CRespond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        devId_ = "";

        seatNum_ = "";

        respondCode_ = 0;

        respondParam_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Respond.internal_static_tvbcloud_CRespond_descriptor;
      }

      public CRespond getDefaultInstanceForType() {
        return CRespond.getDefaultInstance();
      }

      public CRespond build() {
        CRespond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CRespond buildPartial() {
        CRespond result = new CRespond(this);
        result.devId_ = devId_;
        result.seatNum_ = seatNum_;
        result.respondCode_ = respondCode_;
        result.respondParam_ = respondParam_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CRespond) {
          return mergeFrom((CRespond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CRespond other) {
        if (other == CRespond.getDefaultInstance()) return this;
        if (!other.getDevId().isEmpty()) {
          devId_ = other.devId_;
          onChanged();
        }
        if (!other.getSeatNum().isEmpty()) {
          seatNum_ = other.seatNum_;
          onChanged();
        }
        if (other.getRespondCode() != 0) {
          setRespondCode(other.getRespondCode());
        }
        if (!other.getRespondParam().isEmpty()) {
          respondParam_ = other.respondParam_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CRespond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CRespond) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object devId_ = "";
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 1;</code>
       */
      public String getDevId() {
        Object ref = devId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 1;</code>
       */
      public Builder setDevId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 1;</code>
       */
      public Builder clearDevId() {
        
        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端设备id
       * </pre>
       *
       * <code>string devId = 1;</code>
       */
      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devId_ = value;
        onChanged();
        return this;
      }

      private Object seatNum_ = "";
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 2;</code>
       */
      public String getSeatNum() {
        Object ref = seatNum_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          seatNum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSeatNumBytes() {
        Object ref = seatNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          seatNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 2;</code>
       */
      public Builder setSeatNum(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        seatNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 2;</code>
       */
      public Builder clearSeatNum() {
        
        seatNum_ = getDefaultInstance().getSeatNum();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安卓客户端座位号
       * </pre>
       *
       * <code>string seatNum = 2;</code>
       */
      public Builder setSeatNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        seatNum_ = value;
        onChanged();
        return this;
      }

      private int respondCode_ ;
      /**
       * <pre>
       *0.接收投票信息 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求 
       * </pre>
       *
       * <code>int32 respondCode = 3;</code>
       */
      public int getRespondCode() {
        return respondCode_;
      }
      /**
       * <pre>
       *0.接收投票信息 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求 
       * </pre>
       *
       * <code>int32 respondCode = 3;</code>
       */
      public Builder setRespondCode(int value) {
        
        respondCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0.接收投票信息 1.活动开始 2.活动结束 3.检验密码 4.修改密码 5.诊断请求 
       * </pre>
       *
       * <code>int32 respondCode = 3;</code>
       */
      public Builder clearRespondCode() {
        
        respondCode_ = 0;
        onChanged();
        return this;
      }

      private Object respondParam_ = "";
      /**
       * <pre>
       *200.成功   其他失败
       * </pre>
       *
       * <code>string respondParam = 4;</code>
       */
      public String getRespondParam() {
        Object ref = respondParam_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          respondParam_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *200.成功   其他失败
       * </pre>
       *
       * <code>string respondParam = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRespondParamBytes() {
        Object ref = respondParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          respondParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *200.成功   其他失败
       * </pre>
       *
       * <code>string respondParam = 4;</code>
       */
      public Builder setRespondParam(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        respondParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *200.成功   其他失败
       * </pre>
       *
       * <code>string respondParam = 4;</code>
       */
      public Builder clearRespondParam() {
        
        respondParam_ = getDefaultInstance().getRespondParam();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *200.成功   其他失败
       * </pre>
       *
       * <code>string respondParam = 4;</code>
       */
      public Builder setRespondParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        respondParam_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tvbcloud.CRespond)
    }

    // @@protoc_insertion_point(class_scope:tvbcloud.CRespond)
    private static final CRespond DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CRespond();
    }

    public static CRespond getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CRespond>
        PARSER = new com.google.protobuf.AbstractParser<CRespond>() {
      public CRespond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CRespond(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CRespond> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CRespond> getParserForType() {
      return PARSER;
    }

    public CRespond getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tvbcloud_CRespond_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tvbcloud_CRespond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rRespond.proto\022\010tvbcloud\"U\n\010CRespond\022\r\n" +
      "\005devId\030\001 \001(\t\022\017\n\007seatNum\030\002 \001(\t\022\023\n\013respond" +
      "Code\030\003 \001(\005\022\024\n\014respondParam\030\004 \001(\tB>\n\024com." +
      "golding.tvbcloudB\007Respond\252\002\034com.golding." +
      "tvbcloud.Respondb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tvbcloud_CRespond_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tvbcloud_CRespond_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tvbcloud_CRespond_descriptor,
        new String[] { "DevId", "SeatNum", "RespondCode", "RespondParam", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
