// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpgradeInfo.proto

package com.golding.tvbcloud;

public final class Upgrade {
  private Upgrade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CUpgradeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tvbcloud.CUpgrade)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1.apk  2.system
     * </pre>
     *
     * <code>string update_type = 1;</code>
     */
    String getUpdateType();
    /**
     * <pre>
     *1.apk  2.system
     * </pre>
     *
     * <code>string update_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getUpdateTypeBytes();

    /**
     * <pre>
     *apk或是系统版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    String getVersion();
    /**
     * <pre>
     *apk或是系统版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     *升级文件下载地址
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    String getDownloadUrl();
    /**
     * <pre>
     *升级文件下载地址
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getDownloadUrlBytes();

    /**
     * <pre>
     *更新描述
     * </pre>
     *
     * <code>string desc = 4;</code>
     */
    String getDesc();
    /**
     * <pre>
     *更新描述
     * </pre>
     *
     * <code>string desc = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <pre>
     *MD5 checksum
     * </pre>
     *
     * <code>string MD5 = 5;</code>
     */
    String getMD5();
    /**
     * <pre>
     *MD5 checksum
     * </pre>
     *
     * <code>string MD5 = 5;</code>
     */
    com.google.protobuf.ByteString
        getMD5Bytes();
  }
  /**
   * Protobuf type {@code tvbcloud.CUpgrade}
   */
  public  static final class CUpgrade extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tvbcloud.CUpgrade)
      CUpgradeOrBuilder {
    // Use CUpgrade.newBuilder() to construct.
    private CUpgrade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CUpgrade() {
      updateType_ = "";
      version_ = "";
      downloadUrl_ = "";
      desc_ = "";
      mD5_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CUpgrade(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              updateType_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              downloadUrl_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              mD5_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Upgrade.internal_static_tvbcloud_CUpgrade_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Upgrade.internal_static_tvbcloud_CUpgrade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CUpgrade.class, Builder.class);
    }

    public static final int UPDATE_TYPE_FIELD_NUMBER = 1;
    private volatile Object updateType_;
    /**
     * <pre>
     *1.apk  2.system
     * </pre>
     *
     * <code>string update_type = 1;</code>
     */
    public String getUpdateType() {
      Object ref = updateType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *1.apk  2.system
     * </pre>
     *
     * <code>string update_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateTypeBytes() {
      Object ref = updateType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile Object version_;
    /**
     * <pre>
     *apk或是系统版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *apk或是系统版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOWNLOAD_URL_FIELD_NUMBER = 3;
    private volatile Object downloadUrl_;
    /**
     * <pre>
     *升级文件下载地址
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    public String getDownloadUrl() {
      Object ref = downloadUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        downloadUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *升级文件下载地址
     * </pre>
     *
     * <code>string download_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDownloadUrlBytes() {
      Object ref = downloadUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        downloadUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESC_FIELD_NUMBER = 4;
    private volatile Object desc_;
    /**
     * <pre>
     *更新描述
     * </pre>
     *
     * <code>string desc = 4;</code>
     */
    public String getDesc() {
      Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *更新描述
     * </pre>
     *
     * <code>string desc = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MD5_FIELD_NUMBER = 5;
    private volatile Object mD5_;
    /**
     * <pre>
     *MD5 checksum
     * </pre>
     *
     * <code>string MD5 = 5;</code>
     */
    public String getMD5() {
      Object ref = mD5_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mD5_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *MD5 checksum
     * </pre>
     *
     * <code>string MD5 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMD5Bytes() {
      Object ref = mD5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mD5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUpdateTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, updateType_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (!getDownloadUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, downloadUrl_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, desc_);
      }
      if (!getMD5Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mD5_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUpdateTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, updateType_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (!getDownloadUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, downloadUrl_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, desc_);
      }
      if (!getMD5Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mD5_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CUpgrade)) {
        return super.equals(obj);
      }
      CUpgrade other = (CUpgrade) obj;

      boolean result = true;
      result = result && getUpdateType()
          .equals(other.getUpdateType());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getDownloadUrl()
          .equals(other.getDownloadUrl());
      result = result && getDesc()
          .equals(other.getDesc());
      result = result && getMD5()
          .equals(other.getMD5());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UPDATE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateType().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + DOWNLOAD_URL_FIELD_NUMBER;
      hash = (53 * hash) + getDownloadUrl().hashCode();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + MD5_FIELD_NUMBER;
      hash = (53 * hash) + getMD5().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CUpgrade parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CUpgrade parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CUpgrade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CUpgrade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CUpgrade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CUpgrade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CUpgrade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CUpgrade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CUpgrade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CUpgrade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CUpgrade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CUpgrade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CUpgrade prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tvbcloud.CUpgrade}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tvbcloud.CUpgrade)
        CUpgradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Upgrade.internal_static_tvbcloud_CUpgrade_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Upgrade.internal_static_tvbcloud_CUpgrade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CUpgrade.class, Builder.class);
      }

      // Construct using com.golding.tvbcloud.Upgrade.CUpgrade.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        updateType_ = "";

        version_ = "";

        downloadUrl_ = "";

        desc_ = "";

        mD5_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Upgrade.internal_static_tvbcloud_CUpgrade_descriptor;
      }

      public CUpgrade getDefaultInstanceForType() {
        return CUpgrade.getDefaultInstance();
      }

      public CUpgrade build() {
        CUpgrade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CUpgrade buildPartial() {
        CUpgrade result = new CUpgrade(this);
        result.updateType_ = updateType_;
        result.version_ = version_;
        result.downloadUrl_ = downloadUrl_;
        result.desc_ = desc_;
        result.mD5_ = mD5_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CUpgrade) {
          return mergeFrom((CUpgrade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CUpgrade other) {
        if (other == CUpgrade.getDefaultInstance()) return this;
        if (!other.getUpdateType().isEmpty()) {
          updateType_ = other.updateType_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getDownloadUrl().isEmpty()) {
          downloadUrl_ = other.downloadUrl_;
          onChanged();
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (!other.getMD5().isEmpty()) {
          mD5_ = other.mD5_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CUpgrade parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CUpgrade) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object updateType_ = "";
      /**
       * <pre>
       *1.apk  2.system
       * </pre>
       *
       * <code>string update_type = 1;</code>
       */
      public String getUpdateType() {
        Object ref = updateType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *1.apk  2.system
       * </pre>
       *
       * <code>string update_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateTypeBytes() {
        Object ref = updateType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *1.apk  2.system
       * </pre>
       *
       * <code>string update_type = 1;</code>
       */
      public Builder setUpdateType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1.apk  2.system
       * </pre>
       *
       * <code>string update_type = 1;</code>
       */
      public Builder clearUpdateType() {
        
        updateType_ = getDefaultInstance().getUpdateType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1.apk  2.system
       * </pre>
       *
       * <code>string update_type = 1;</code>
       */
      public Builder setUpdateTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateType_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <pre>
       *apk或是系统版本号
       * </pre>
       *
       * <code>string version = 2;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *apk或是系统版本号
       * </pre>
       *
       * <code>string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *apk或是系统版本号
       * </pre>
       *
       * <code>string version = 2;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *apk或是系统版本号
       * </pre>
       *
       * <code>string version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *apk或是系统版本号
       * </pre>
       *
       * <code>string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private Object downloadUrl_ = "";
      /**
       * <pre>
       *升级文件下载地址
       * </pre>
       *
       * <code>string download_url = 3;</code>
       */
      public String getDownloadUrl() {
        Object ref = downloadUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          downloadUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *升级文件下载地址
       * </pre>
       *
       * <code>string download_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDownloadUrlBytes() {
        Object ref = downloadUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          downloadUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *升级文件下载地址
       * </pre>
       *
       * <code>string download_url = 3;</code>
       */
      public Builder setDownloadUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        downloadUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *升级文件下载地址
       * </pre>
       *
       * <code>string download_url = 3;</code>
       */
      public Builder clearDownloadUrl() {
        
        downloadUrl_ = getDefaultInstance().getDownloadUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *升级文件下载地址
       * </pre>
       *
       * <code>string download_url = 3;</code>
       */
      public Builder setDownloadUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        downloadUrl_ = value;
        onChanged();
        return this;
      }

      private Object desc_ = "";
      /**
       * <pre>
       *更新描述
       * </pre>
       *
       * <code>string desc = 4;</code>
       */
      public String getDesc() {
        Object ref = desc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *更新描述
       * </pre>
       *
       * <code>string desc = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *更新描述
       * </pre>
       *
       * <code>string desc = 4;</code>
       */
      public Builder setDesc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新描述
       * </pre>
       *
       * <code>string desc = 4;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *更新描述
       * </pre>
       *
       * <code>string desc = 4;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private Object mD5_ = "";
      /**
       * <pre>
       *MD5 checksum
       * </pre>
       *
       * <code>string MD5 = 5;</code>
       */
      public String getMD5() {
        Object ref = mD5_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mD5_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *MD5 checksum
       * </pre>
       *
       * <code>string MD5 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMD5Bytes() {
        Object ref = mD5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mD5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *MD5 checksum
       * </pre>
       *
       * <code>string MD5 = 5;</code>
       */
      public Builder setMD5(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mD5_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *MD5 checksum
       * </pre>
       *
       * <code>string MD5 = 5;</code>
       */
      public Builder clearMD5() {
        
        mD5_ = getDefaultInstance().getMD5();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *MD5 checksum
       * </pre>
       *
       * <code>string MD5 = 5;</code>
       */
      public Builder setMD5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mD5_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tvbcloud.CUpgrade)
    }

    // @@protoc_insertion_point(class_scope:tvbcloud.CUpgrade)
    private static final CUpgrade DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CUpgrade();
    }

    public static CUpgrade getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CUpgrade>
        PARSER = new com.google.protobuf.AbstractParser<CUpgrade>() {
      public CUpgrade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CUpgrade(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CUpgrade> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CUpgrade> getParserForType() {
      return PARSER;
    }

    public CUpgrade getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tvbcloud_CUpgrade_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tvbcloud_CUpgrade_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021UpgradeInfo.proto\022\010tvbcloud\"a\n\010CUpgrad" +
      "e\022\023\n\013update_type\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022" +
      "\024\n\014download_url\030\003 \001(\t\022\014\n\004desc\030\004 \001(\t\022\013\n\003M" +
      "D5\030\005 \001(\tB<\n\024com.golding.tvbcloudB\007Upgrad" +
      "e\252\002\032com.golding.tvbcloud.Logonb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tvbcloud_CUpgrade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tvbcloud_CUpgrade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tvbcloud_CUpgrade_descriptor,
        new String[] { "UpdateType", "Version", "DownloadUrl", "Desc", "MD5", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
